version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    
    volumes:
      - ..:/workspace:cached
    
    command: sleep infinity

    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    ## Uncomment below lines for persistent database
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: media_match
      POSTGRES_USER: media_match
      POSTGRES_PASSWORD: hunter2

## Uncomment below lines for persistent database
# volumes:
#   postgres-data:
