name: OpenAPI Preview

on:
  pull_request:
    paths:
      - 'openapi/openapi.yaml' # Trigger only if openapi.yaml in the openapi/ dir changes

jobs:
  build-and-deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # To comment on the PR
      contents: read       # To checkout the repository
      id-token: write      # If using OIDC for AWS authentication (recommended)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (for ReDocly CLI)
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Or your preferred LTS version

      - name: Install ReDocly CLI
        run: npm install -g @redocly/cli

      - name: Build HTML documentation
        run: redocly build-docs openapi/openapi.yaml -o openapi-preview.html

      - name: Configure AWS credentials (OIDC - Recommended)
        uses: aws-actions/configure-aws-credentials@v2 
        with:
          role-to-assume: arn:aws:iam::YOUR_AWS_ACCOUNT_ID:role/YOUR_GITHUB_ACTIONS_S3_DEPLOY_ROLE # Replace with your IAM role
          aws-region: YOUR_AWS_REGION # e.g., us-east-1

      # Alternative: Configure AWS credentials (Access Keys - Less Secure)
      # - name: Configure AWS credentials (Access Keys)
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: YOUR_AWS_REGION

      - name: Upload HTML to S3
        id: s3_upload
        run: |
          PR_NUMBER=$(echo "${{ github.event.pull_request.number }}")
          S3_PATH="s3://YOUR_S3_BUCKET_NAME/openapi-previews/pr-${PR_NUMBER}/openapi-preview.html"
          aws s3 cp openapi-preview.html "${S3_PATH}" --acl public-read # Or adjust ACL as needed
          echo "PREVIEW_URL=https://YOUR_S3_BUCKET_NAME.s3.YOUR_AWS_REGION.amazonaws.com/openapi-previews/pr-${PR_NUMBER}/openapi-preview.html" >> $GITHUB_OUTPUT
        # Replace YOUR_S3_BUCKET_NAME and YOUR_AWS_REGION
        # Note: The S3 URL format can vary based on your S3 settings (e.g., path-style vs virtual-hosted). Adjust accordingly.

      - name: Comment on PR with Preview URL
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const previewUrl = "${{ steps.s3_upload.outputs.PREVIEW_URL }}";
            const issue_number = context.issue.number;
            const commentBody = `
              OpenAPI documentation preview for this PR:
              [View Preview](${previewUrl})

              *Note: This preview is automatically generated whenever \`openapi/openapi.yaml\` is updated.*
            `;

            // Check if a comment with a similar header already exists
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
            });

            const botCommentMarker = "OpenAPI documentation preview for this PR:";
            const existingComment = comments.find(comment => comment.user.login === 'github-actions[bot]' && comment.body.includes(botCommentMarker));

            if (existingComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: commentBody,
              });
              console.log(`Updated existing comment on PR #${issue_number}.`);
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: commentBody,
              });
              console.log(`Created new comment on PR #${issue_number}.`);
            }