source /etc/bash.bashrc

# Make path respect local binaries from pip
export PATH=$PATH:~/.local/bin

# Add directory containing hmalib to PYTHONPATH. This allows vscode
# testdiscovery to work
export PYTHONPATH=$PYTHONPATH:/workspaces/ThreatExchange/python-threatexchange

# Last line must have a newline char!
