export SAVEHIST=10000000

# Allow history file to be sooper large
export HISTFILESIZE=1000000000

# Allow zsh to load as much history as it needs 
export HISTSIZE=1000000000

# Incrementally add to the history file.
setopt INC_APPEND_HISTORY

# Make path respect local binaries from pip
export PATH=$PATH:~/.local/bin

# Add directory containing hmalib to PYTHONPATH. This allows vscode
# testdiscovery to work
export PYTHONPATH=$PYTHONPATH:/workspaces/ThreatExchange/hasher-matcher-actioner

# Last line must have a newline char!
