version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    
    volumes:
      - ..:/workspace:cached
    
    command: sleep infinity

    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
        - ./pg-scripts/init-multiple-pg-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-pg-dbs.sh
    ## Uncomment below lines for persistent database
    #   - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: media_match
      POSTGRES_PASSWORD: hunter2
      POSTGRES_MULTIPLE_DATABASES: media_match,media_match_test

## Uncomment below lines for persistent database
# volumes:
#   postgres-data:
