java_library(
    name = "hasher",
    srcs = glob(["*.java"]),
    deps = [
        "//src/main/java/pdqhashing/types:types",
        "//src/main/java/pdqhashing/utils:utils",
    ],
    visibility = ["//src:__subpackages__"],
)
