"""empty message

Revision ID: 4aa72e772bd9
Revises: f44e60a6a050
Create Date: 2023-10-04 19:08:08.228005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4aa72e772bd9"
down_revision = "f44e60a6a050"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("signal_type_override", schema=None) as batch_op:
        batch_op.drop_constraint("signal_type_override_name_key", type_="unique")
        batch_op.create_index(
            batch_op.f("ix_signal_type_override_name"), ["name"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("signal_type_override", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_signal_type_override_name"))
        batch_op.create_unique_constraint("signal_type_override_name_key", ["name"])

    # ### end Alembic commands ###
