"""empty message

Revision ID: 76896c08b4ff
Revises: b44643ee7ef0
Create Date: 2023-09-29 13:39:57.921301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76896c08b4ff'
down_revision = 'b44643ee7ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('fetching_enabled', sa.Boolean(), nullable=False),
    sa.Column('seen_enabled', sa.Boolean(), nullable=False),
    sa.Column('report_true_positive', sa.Boolean(), nullable=False),
    sa.Column('report_false_positive', sa.Boolean(), nullable=False),
    sa.Column('additional_config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchanges')
    # ### end Alembic commands ###
