"""empty message

Revision ID: 7b7c6420f31d
Revises: 76896c08b4ff
Create Date: 2023-09-29 14:27:39.175075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b7c6420f31d'
down_revision = '76896c08b4ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchanges', schema=None) as batch_op:
        batch_op.alter_column('additional_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchanges', schema=None) as batch_op:
        batch_op.alter_column('additional_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)

    # ### end Alembic commands ###
