"""empty message

Revision ID: 9d85c5274e1f
Revises: b44643ee7ef0
Create Date: 2023-09-29 22:42:30.984931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9d85c5274e1f"
down_revision = "b44643ee7ef0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("enabled_ratio", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "collaboration_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("api_cls", sa.String(length=255), nullable=False),
        sa.Column("fetching_enabled", sa.Boolean(), nullable=False),
        sa.Column("typed_config", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "bank_content",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bank_id", sa.Integer(), nullable=False),
        sa.Column("disable_until_ts", sa.Integer(), nullable=False),
        sa.Column("original_content_uri", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bank_id"],
            ["bank.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "content_signal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("signal_type", sa.String(), nullable=False),
        sa.Column("signal_val", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["bank_content.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("hashes")
    op.drop_table("banks")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "banks",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="banks_pkey"),
    )
    op.create_table(
        "hashes",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("value", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="hashes_pkey"),
    )
    op.drop_table("content_signal")
    op.drop_table("bank_content")
    op.drop_table("collaboration_config")
    op.drop_table("bank")
    # ### end Alembic commands ###
