"""empty message

Revision ID: 9f866454e577
Revises: 9d85c5274e1f
Create Date: 2023-10-04 00:23:47.225506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9f866454e577"
down_revision = "9d85c5274e1f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signal_index",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("signal_type", sa.String(), nullable=False),
        sa.Column("serialized_index", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "signal_type_override",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("enabled_ratio", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("content_signal", schema=None) as batch_op:
        batch_op.drop_column("id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("content_signal", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
        )

    op.drop_table("signal_type_override")
    op.drop_table("signal_index")
    # ### end Alembic commands ###
