"""empty message

Revision ID: f44e60a6a050
Revises: 9f866454e577
Create Date: 2023-10-04 18:56:43.270853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f44e60a6a050"
down_revision = "9f866454e577"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("signal_index", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("signal_index", schema=None) as batch_op:
        batch_op.drop_column("updated_at")

    # ### end Alembic commands ###
