#! /usr/bin/env python3
# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved

"""
Write simple configs to the HMA config database
"""

import argparse
import json
import tempfile
import subprocess


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "in_file",
        type=argparse.FileType(),
        help="file to read items from",
    )
    parser.add_argument(
        "table_name",
        help="Name of the config table to add to",
    )

    args = parser.parse_args()
    rows = json.load(args.in_file)
    with tempfile.NamedTemporaryFile("w", delete=False) as tmp:
        # Rewrite so the table name is the key of dicts with these as the results
        json.dump({args.table_name: rows}, tmp)
    # Windows environments require file not be held
    subprocess.check_call(
        [
            "aws",
            "dynamodb",
            "batch-write-item",
            "--request-items",
            f"file://{tmp.name}",
        ]
    )
