name: HMA Pull Request Terraform Validator
on:
  pull_request_target:
    paths:
      - "hasher-matcher-actioner/**"
      - ".github/workflows/hma-pull-request.yaml"

defaults:
  run:
    working-directory: hasher-matcher-actioner

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.x
      - name: Check format
        run: terraform fmt -check -diff -recursive -no-color
        continue-on-error: true
      - name: Init Modules
        run: terraform init
      - name: Validate terraform files
        run: terraform validate -no-color
