name: HMA Main push
on:
  push:
    branches:
      - main
    paths:
      - "hasher-matcher-actioner/**"
      - ".github/workflows/hma-ci-main-push.yaml"
defaults:
  run:
    working-directory: hasher-matcher-actioner/terraform

jobs:
  tf_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.x
      - name: Check format
        run: terraform fmt -check -diff -recursive -no-color
        continue-on-error: true
      - name: Init Modules
        run: terraform init -input=false
      - name: Validate terraform files
        run: terraform validate -no-color
