name: HMA Pull Request Terraform Validator
on:
  pull_request:
    paths:
      - "hasher-matcher-actioner/**"
      - ".github/workflows/hma-ci-pull-request.yaml"

defaults:
  run:
    working-directory: hasher-matcher-actioner

jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.x
      - name: Check format
        run: terraform fmt -check -diff -recursive -no-color
        continue-on-error: true
      - name: Init Modules
        run: terraform init
      - name: Validate terraform files
        run: terraform validate -no-color
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Check code format
        run: |
          black --check .
  type-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Check python types
        run: |
          mypy hmalib
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Test with pytest
        run: |
          py.test
