# Copyright (c) Meta Platforms, Inc. and affiliates.

name: Publish HMA docker image

on:
  push:
    branches:
      - main
    paths:
      - "hasher-matcher-actioner/version.txt"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

defaults:
  run:
    working-directory: hasher-matcher-actioner

jobs:
  build-and-push:
    name: Build and Publish Docker Image to registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read version and lowercase image name
        id: version
        run: |
          echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV
          echo "IMAGE_NAME_LC=${IMAGE_NAME,,}" >>${GITHUB_ENV}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          provenance: false
          context: hasher-matcher-actioner
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}/hma:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}/hma:${{ env.VERSION }}
