# Copyright (c) Meta Platforms, Inc. and affiliates.

name: hasher-matcher-actioner-webapp CI
on:
  push:
    branches:
      - main
    paths:
      - "hasher-matcher-actioner/webapp/**"
      - ".github/workflows/hma-webapp-ci.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "hasher-matcher-actioner/webapp/**"
      - ".github/workflows/hma-webapp-ci.yaml"

defaults:
  run:
    working-directory: hasher-matcher-actioner/webapp

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: |
          npx eslint src --ext .js,.jsx,.tsx
      - name: Run Prettier
        run: |
          npx prettier --check src
