name: hasher-matcher-actioner-hmalib CI
on:
  push:
    branches:
      - main
    paths:
      - "hasher-matcher-actioner/hmalib/**"
      - ".github/workflows/hamlib-ci.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "hasher-matcher-actioner/hmalib/**"
      - ".github/workflows/hamlib-ci.yaml"

defaults:
  run:
    working-directory: hasher-matcher-actioner/hmalib

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Check code format
        run: |
          black --check .
