# Copyright (c) Meta Platforms, Inc. and affiliates.

name: vpdq python CI
on:
  push:
    branches:
      - main
    paths:
      - "vpdq/python/**"
      - "vpdq/cpp/**"
      - ".github/workflows/vpdq-ci-python.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "vpdq/python/**"
      - "vpdq/cpp/**"
      - ".github/workflows/vpdq-ci-python.yaml"

defaults:
  run:
    working-directory: vpdq

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.x']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install ffmpeg
        id: ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libavcodec-dev libavformat-dev libavdevice-dev libavutil-dev libswscale-dev libswresample-dev libavfilter-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          python3 vpdq-release.py -i
      - name: Test with pytest
        run: |
          python -m pytest
